services:
    _defaults: { public: false, autowire: true, autoconfigure: true }
    App\Application\ExtensionsBundle\Controller\:
        resource: '%kernel.project_dir%/src/Application/ExtensionsBundle/Controller'
        autowire: true
        tags: ['controller.service_arguments']
    admin.extensions:
        class: App\Application\ExtensionsBundle\Admin\ExtensionsAdmin
        tags:
            - { name:  sonata.admin, manager_type: orm, group: Ustawienia, label: Extensions}
        arguments:
            - null
            - null
            - App\Application\ExtensionsBundle\Controller\ExtensionsCRUDController
        public: true