services:
    admin.settings_new:
        class: App\Application\SettingsBundle\Admin\SettingsAdmin
        tags:
            - { name:  sonata.admin, manager_type: orm, group: Ustawienia, label: Ustawienia}
        arguments: [~, App\Application\SettingsBundle\Entity\Settings, ~]
        public: true

    myproject.twig.toolbox_extension:
        class: App\Application\SettingsBundle\Twig\PathExtension
        # Inject doctrine as first parameter
        arguments:
          ["@doctrine","@service_container","@twig.loader.filesystem"]
        tags:
          -  { name: twig.extension }

    sonata.block.service.users:
        class: App\Application\SettingsBundle\Block\UsersBlockService
        arguments:
          [~, "@templating","@doctrine"]
        tags:
        - { name: "sonata.block" }

    settings.new:
        class: App\Application\SettingsBundle\Service\Settings_Get
        arguments:
          ["@doctrine"]
        public: true