<?php

namespace App\Application\Sonata\UserBundle\Entity;

use Sonata\UserBundle\Entity\BaseUser as BaseUser;

/**
 * This file has been generated by the SonataEasyExtendsBundle.
 *
 * @link https://sonata-project.org/easy-extends
 *
 * References:
 * @link http://www.doctrine-project.org/projects/orm/2.0/docs/reference/working-with-objects/en
 */
class User extends BaseUser
{
    /**
     * @var int $id
     */
    protected $id;

    /**
     * @var int $id
     */
    protected $facebookUid;

    protected $twitterName;

    protected $twitterUid;

    /**
     * Get id.
     *
     * @return int $id
     */
    public function getId()
    {
        return $this->id;
    }

    public function getFacebookUid()
    {
        return parent::getFacebookUid(); // TODO: Change the autogenerated stub
    }

    public function setLocale($locale)
    {
        return parent::setLocale($locale); // TODO: Change the autogenerated stub
    }

    public function getLocale()
    {
        return parent::getLocale(); // TODO: Change the autogenerated stub
    }

    public function getTwitterUid()
    {
        return parent::getTwitterUid(); // TODO: Change the autogenerated stub
    }

    public function getTwitterName()
    {
        return parent::getTwitterName(); // TODO: Change the autogenerated stub
    }

}
